Trip.destroy_all
PackingList.destroy_all 

Trip.create([
    {
    name: "Mt. Zirkel Wilderness",
    location: "Walden, CO 80480",
    image: "https://cdn-assets.alltrails.com/uploads/photo/image/30268891/large_8bff4529da20d207850b64a03fbccf0d.jpg",
    start_date: "07-01-2008",
    end_date: "07-03-2008",
    category: "Backpacking",
    miles: 12,
    difficulty: "Moderate",
    rating: 4,
    notes: "Had slide waterfall!"
    },
    {
    "name": "Rawah Wilderness",
    "location": "Jelm, CO 82063",
    "image": "https://preview.redd.it/pn8o38tnmfg31.jpg?width=960&crop=smart&auto=webp&s=f95e32271befda1171df50c11396e03ae5aad624",
    "start_date": "2007-08-03",
    "end_date": "2007-08-05",
    "category": "backpacking",
    "miles": 13,
    "difficulty": "moderate",
    "rating": 88,
    "notes": "amazing!",
    "id": 2
    },
    {
    "name": "Virginia Triple Crown",
    "location": "Gainesville, VA 20155",
    "image": "https://static.getmatcha.com/image/upload/s--cF6Wwybf--/f_auto,q_auto,t_rr_large_traditional/ejmcwrgiuykdawtsuqm4.jpg",
    "start_date": "2017-09-04",
    "end_date": "2017-09-08",
    "category": "backpacking",
    "miles": 19,
    "difficulty": "difficult",
    "rating": 99,
    "notes": "super hard!",
    "id": 3
    }
])

PackingList.create([
    {
    name: "General backpacking list - Rawah",
    trip_id: 2,
    list: [
        "Food",
        "Day pack", 
        "Backpack" ,
        "Tent",
        "Tent stakes", 
        "Sleeping bag",
        "Sleeping pad",
        "Pack cover",
        "Headlamp",
        "First aid kit",
        "Toilet paper" ,
        "Matches/flint" ,
        "Duct tape",
        "Knife/multi-tool",
        "Rope/cord/bungee",
        "Fuel" ,
        "Bear bag" ,
        "Pots" ,
        "Cups",
        "Utensils",
        "Water treatment device" ,
        "Trash bag",
        "Water bottles" ,
        "Water bladders" ,
        "Instant coffee",
        "Sunglasses" ,
        "Hat",
        "Rain gear" ,
        "Camp sandals" ,
        "Hiking shoes",
        "Hiking socks" ,
        "Sweatshirt" ,
        "Long underwear" ,
        "Gloves" ,
        "Swimsuit",
        "Bandanas",
        "Sunscreen" ,
        "Bug spray" ,
        "Wet wipes",
        "Toiletries",
        "Chapstick",
        "Deodorant",
        "Quick-dry towel",
        "Hand sanitizer",
        "Soap" ,
        "Season parks pass",
        "Map/directions",
        "Compass" ,
        "Cell phone",
        "Cash",
        "Book/entertainment",
        "Tarp"
    ]},
    {
    name: "General camping list - Mt. Zirkel",
    trip_id: 1,
    list: [
        "Food",
        "Foil",
        "Paper towel",
        "Tongs",
        "Camp chair",
        "Day pack", 
        "Backpack" ,
        "Tent",
        "Tent stakes", 
        "Sleeping bag",
        "Sleeping pad",
        "Hammock",
        "Hammock strings",
        "Pack cover",
        "Tarp",
        "Headlamp",
        "First aid kit",
        "Extra batteries",
        "Toilet paper" ,
        "Matches/flint" ,
        "Duct tape",
        "Knife/multi-tool",
        "Collapsible sink",
        "Rope/cord/bungee",
        "Lantern",
        "Fuel" ,
        "Bear bag" ,
        "Pots" ,
        "Cups",
        "Utensils",
        "Water treatment device" ,
        "Trash bag",
        "Water bottles" ,
        "Coffee maker",
        "Coffee filters",
        "Water bladders" ,
        "Sunglasses" ,
        "Hat",
        "Rain gear" ,
        "Camp sandals" ,
        "Hiking shoes",
        "Hiking socks" ,
        "Sweatshirt" ,
        "Long underwear" ,
        "Gloves" ,
        "Swimsuit",
        "Bandanas",
        "Sunscreen" ,
        "Bug spray" ,
        "Wet wipes",
        "Toiletries",
        "Chapstick",
        "Deodorant",
        "Quick-dry towel",
        "Hand sanitizer",
        "Soap" ,
        "Season parks pass",
        "Map/directions",
        "Compass" ,
        "Cell phone",
        "Cash",
        "Book/entertainment",
        "Picnic blanket"
    ]
    },
    {
    name: "General camping list - VA Triple Crown",
    trip_id: 3,
    list: [
        "Food",
        "Foil",
        "Paper towel",
        "Tongs",
        "Camp chair",
        "Day pack", 
        "Backpack" ,
        "Tent",
        "Tent stakes", 
        "Sleeping bag",
        "Sleeping pad",
        "Hammock",
        "Hammock strings",
        "Pack cover",
        "Tarp",
        "Headlamp",
        "First aid kit",
        "Extra batteries",
        "Toilet paper" ,
        "Matches/flint" ,
        "Duct tape",
        "Knife/multi-tool",
        "Collapsible sink",
        "Rope/cord/bungee",
        "Lantern",
        "Fuel" ,
        "Bear bag" ,
        "Pots" ,
        "Cups",
        "Utensils",
        "Water treatment device" ,
        "Trash bag",
        "Water bottles" ,
        "Coffee maker",
        "Coffee filters",
        "Water bladders" ,
        "Sunglasses" ,
        "Hat",
        "Rain gear" ,
        "Camp sandals" ,
        "Hiking shoes",
        "Hiking socks" ,
        "Sweatshirt" ,
        "Long underwear" ,
        "Gloves" ,
        "Swimsuit",
        "Bandanas",
        "Sunscreen" ,
        "Bug spray" ,
        "Wet wipes",
        "Toiletries",
        "Chapstick",
        "Deodorant",
        "Quick-dry towel",
        "Hand sanitizer",
        "Soap" ,
        "Season parks pass",
        "Map/directions",
        "Compass" ,
        "Cell phone",
        "Cash",
        "Book/entertainment",
        "Picnic blanket"
    ]
    }
])
